## A4 - Exercícios Numpy (Parte 2)

<hr />

In [3]:
import numpy as np

10 - Matriz Identidade

Seja M uma matriz quadrada de ordem n. A matriz M é chamada de Matriz Identidade de ordem n (indicada por In) quando os elementos da diagonal principal são todos iguais a 1 e os elementos restantes são iguais a zero.

**Desenvolva** uma função que retorne a matriz identidade de dimensão n.

Exemplo de matriz identidade de dimensão 3x3:
```
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
```

Exemplo de matriz identidade de dimensão 5x5:
```
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])
```    


11 - Considere os arrays a e b, descubra os índices dos elementos com o mesmo valor.

In [4]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

12 - Crie um array de 2 dimensões (5 X 3) contendo números aleatórios decimais entre 5 e 10.

13 - Dado o array a, efetue a divisão do menor valor pelo maior valor de cada linha.

In [91]:
np.random.seed(100)
a = np.random.randint(1,10, [5,4])
a

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5]])

14 - Elimine os NAN do array a.

In [94]:
a = np.array([[1, np.nan, 3], [np.nan, 5, 6], [7, 8, np.nan]])
a

array([[ 1., nan,  3.],
       [nan,  5.,  6.],
       [ 7.,  8., nan]])

15 - Dado o array a de 3 dimensões e o array b de uma dimensão apenas. Subtraia o array b do array a, de forma que cada elemento do array b subtraia a __linha__ correspondente do array a.

In [97]:
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
a

array([[3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [98]:
b = np.array([1,2,3])
b

array([1, 2, 3])