# Bibioteca NumPy
<hr />

* NumPy é uma biblioteca open source especializada em operações de Álgebra Linear em Python.

* "Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes." [WikiPedia](https://pt.wikipedia.org/wiki/%C3%81lgebra_linear).

* É amplamente utilizada na maioria de outras bibliotecas de análise de dados.

* Seus principais métodos foram desenvolvidos em linguagem C, o que garante alto desempenho, mesmo em vetores com grandes quantidades de informações.

* Sua instalação pode ser feita através do pip ou do conda:
    ```javascript
        pip install numpy ou conda install numpy
    ```


* NumPy Arrays é a principal ferramenta da biblioteca.

* Arrays em NumPy podem ser VETORES ou MATRIZES.

* Vetores são arrays de uma única dimensão, enquato matrizes são arrays de múltiplas dimensões (porém pode existir uma matriz com apenas uma linha ou uma coluna).

* Matrizes podem ser encontradas em objetos comuns do dia a dia como por exemplo uma TV, nada mais é do que uma matriz de pixels, um tabuleiro de xadrez, a tela de um smartfone.

**A primeira tarefa a ser efetuada é importar a biblioteca NumPy. É muito comum criar um alias para o import, facilitando sua utilização.**

In [ ]:
import numpy as np

## Criando arrays a partir de listas

In [ ]:
lista = [1, 2, 3]

In [ ]:
lista

[1, 2, 3]

In [ ]:
np.array(lista)

array([1, 2, 3])

## Criando matrizes a partir de listas

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Principais Métodos NumPy

### Método: **arange()**
Semelhante ao range do Python, porém devolve um array com os elementos que estão dentro do intervalo selecionado.

*Dica: ao digitar o nome do método, o comando shift+tab mostra a documentação!*

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Método: zeros()

Retorna uma matriz com a dimensão informada, preenchido com zeros.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

O tipo padrão é float, porém pode ser alterado pelo parâmetro **dtype**.

In [ ]:
np.zeros(3, dtype=int)

array([0, 0, 0])

Para uma matriz com mais de uma dimensão, o parâmetro com as dimensões deverá ser uma tupla.

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

### Método: ones()

Da mesma forma do método *zeros()*, retorna uma matriz com a dimensão informada, preenchida com 1.

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [ ]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

### Método: linspace()

Cria uma sequencia de números igualmente espaçados entre os limites dados.

In [ ]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [ ]:
np.linspace(0, 100, 10, dtype=int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

### Método: eye()

Retorna a **matriz identidade** com a dimensão informada.

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Sub-biblioteca random

Sub-biblioteca do NumPy com diversos métodos para geração de números aleatórios.

### Método: rand()

Retorna uma matriz com a dimensão informada, preenchidas com números aleatórios de 0 a 1 seguindo uma distribuição uniforme (probabilidade).

In [ ]:
np.random.rand(5)

array([0.77028028, 0.08338125, 0.76587906, 0.75947616, 0.84943464])

In [ ]:
np.random.rand(5, 3)

array([[0.24032688, 0.46230013, 0.16114638],
       [0.06224451, 0.80678743, 0.86848449],
       [0.40870637, 0.76608796, 0.04757039],
       [0.13889273, 0.41914059, 0.82827447],
       [0.10214587, 0.92713461, 0.5711761 ]])

É possível incluir operações na criação de números aleatórios

In [ ]:
np.random.rand(5) * 100

array([62.72877627, 56.80376166, 99.02733415, 15.83596697, 54.24129878])

In [ ]:
np.random.rand(3, 3) * 10

array([[4.29479305, 9.92991951, 7.32300703],
       [2.3164508 , 3.26495804, 6.8884988 ],
       [6.83885297, 2.58178595, 0.41550512]])

### Método: randn()

Retorna uma matriz com a dimensão informada, preenchida com números aleatórios, seguindo uma distribuição normal.

In [ ]:
np.random.randn(5)

array([ 0.41507826, -0.2625471 ,  0.92304606,  0.70784009, -0.13318735])

In [ ]:
np.random.randn(3, 4)

array([[-0.366793  , -0.13745029, -1.28792535, -0.49006591],
       [-1.27594738,  1.68943302,  0.84084823,  0.18803447],
       [ 1.3982089 ,  0.09126579,  1.42020217,  0.70843654]])

In [ ]:
np.random.randn(5) * 100

array([-158.46360917,  -15.6152184 ,   62.24038707,  -85.47119014,
        112.30409706])

### Método: randint()

Retorna um número inteiro aleatório entre o intervalo informado ou uma matriz unidimensional, preenchida com números aleatórios inteiros, entre o intervalo informado.

In [ ]:
np.random.randint(1, 10)

1

In [ ]:
np.random.randint(1, 100, 15)

array([72, 34, 13, 12, 86, 22, 47,  4, 72, 45, 51, 87, 88, 39, 73])

## Métodos e atributos do objeto NumPy Array

### Método: reshape()

Reorganiza um array em uma dimensão diferente da original.

In [ ]:
myarray = np.random.rand(10)

In [ ]:
myarray

array([0.18075598, 0.80571396, 0.72429486, 0.81024509, 0.57301299,
       0.20606127, 0.35330129, 0.7693978 , 0.69625259, 0.09567658])

In [ ]:
myarray.reshape(2, 5)

array([[0.18075598, 0.80571396, 0.72429486, 0.81024509, 0.57301299],
       [0.20606127, 0.35330129, 0.7693978 , 0.69625259, 0.09567658]])

In [ ]:
myarray.reshape(5, 2)

array([[0.18075598, 0.80571396],
       [0.72429486, 0.81024509],
       [0.57301299, 0.20606127],
       [0.35330129, 0.7693978 ],
       [0.69625259, 0.09567658]])

In [ ]:
myarray.reshape(2, 5).reshape(10)

array([0.18075598, 0.80571396, 0.72429486, 0.81024509, 0.57301299,
       0.20606127, 0.35330129, 0.7693978 , 0.69625259, 0.09567658])

### Método: max()

Retorna o maior valor dentro de um array.

In [ ]:
myarray.max()

0.8102450871747433

### Método: argmax()

Retorna o índice do maior valor dentro de um array.

In [ ]:
myarray.argmax()

3

In [ ]:
myarray[2]

0.7242948611225084

### Método: min()

Retorna o menor valor dentro de um array.

In [ ]:
myarray.min()

0.09567657906378779

### Método: argmin()

Retorna o índice do menor valor dentro de um array.

In [ ]:
myarray.argmin()

9

In [ ]:
myarray[6]

0.35330129419313083

### Atributo: shape

Retorna o formado do array.

In [ ]:
myarray.shape

(10,)

In [ ]:
a = np.random.rand(3, 4)

In [ ]:
a

array([[0.1236517 , 0.95277893, 0.86098205, 0.4928001 ],
       [0.10052892, 0.39155475, 0.66252944, 0.93460328],
       [0.14932742, 0.45338379, 0.21990119, 0.58865309]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a = a.reshape(2, 6)

In [ ]:
a

array([[0.1236517 , 0.95277893, 0.86098205, 0.4928001 , 0.10052892,
        0.39155475],
       [0.66252944, 0.93460328, 0.14932742, 0.45338379, 0.21990119,
        0.58865309]])

In [ ]:
a.shape

(2, 6)

## Mais métodos do objeto NumPy Array

### Método: mean()
Retorna a média aritmética simples dos elementos do array

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.mean()

2.5

In [ ]:
a = np.array([
    [[1, 2], [3, 4], [5, 6]]
  ])

In [ ]:
a.mean()

3.5

### Método: std()
Retorna o desvio padrão

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.std()

1.118033988749895

In [ ]:
a = np.array([[[1, 2], [3, 4], [99, 777]]])

In [ ]:
a.std()

283.64512256613114

### Método: sum()

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a = np.array([[1, 2], [3, 4], [99, 777]])
a

array([[  1,   2],
       [  3,   4],
       [ 99, 777]])

In [ ]:
a.sum()

886

In [ ]:
a.sum(axis=0)

array([103, 783])

In [ ]:
a.sum(axis=1)

array([  3,   7, 876])

## Inserindo e excluindo elementos

### Inserindo elementos de um array unidimensional

In [ ]:
arr = np.array([1, 2, 3, 5, 6, 7, 8])
arr

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
np.insert(arr, 3, 4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.insert(arr, 3, [99, 98, 88, 55])

array([ 1,  2,  3, 99, 98, 88, 55,  5,  6,  7,  8])

In [ ]:
np.insert(arr, (3, 6), [88, 55])

array([ 1,  2,  3, 88,  5,  6,  7, 55,  8])

### Inserindo elementos de um array bidimensional

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.insert(arr, [1], [[6],[9],], axis = 0) # Inserindo a partir da linha 1, duas novas linhas com valores 6 e 9 (tanto faz o índice estar entre '[]')

array([[ 0,  1,  2,  3],
       [ 6,  6,  6,  6],
       [ 9,  9,  9,  9],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.insert(arr, [1], [6, 9, 8, 12], axis = 0) # Inserindo na linha 1, uma nova linha com os valores 6, 9, 8 e 12 (tanto faz o índice estar entre '[]')

array([[ 0,  1,  2,  3],
       [ 6,  9,  8, 12],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.insert(arr, 1, [[6], [9], [8], [12],], axis = 0) # Inserindo a partir da linha 1, novas linhas com os valores 6, 9, 8 e 12

array([[ 0,  1,  2,  3],
       [ 6,  6,  6,  6],
       [ 9,  9,  9,  9],
       [ 8,  8,  8,  8],
       [12, 12, 12, 12],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.insert(arr, 1, [[8],[7],[9]], axis = 1) # Inserindo a partir da coluna 1, novas colunas com os valores 8, 7 e 9

array([[ 0,  8,  7,  9,  1,  2,  3],
       [ 4,  8,  7,  9,  5,  6,  7],
       [ 8,  8,  7,  9,  9, 10, 11]])

In [ ]:
np.insert(arr, [1], [8, 7, 9], axis = 1)

array([[ 0,  8,  7,  9,  1,  2,  3],
       [ 4,  8,  7,  9,  5,  6,  7],
       [ 8,  8,  7,  9,  9, 10, 11]])

In [ ]:
np.insert(arr, [1], [[8],[7],[9]], axis = 1) # Inserindo naa coluna 1, uma nova coluna com os valores 8, 7 e 9

array([[ 0,  8,  1,  2,  3],
       [ 4,  7,  5,  6,  7],
       [ 8,  9,  9, 10, 11]])

In [ ]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.insert(arr, (2, 4), 9)

array([0, 1, 9, 2, 3, 9, 4, 5])

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.insert(arr, (0, 3), 66, axis = 1)

array([[66,  0,  1,  2, 66,  3],
       [66,  4,  5,  6, 66,  7],
       [66,  8,  9, 10, 66, 11]])

### Excluindo elementos de um array unidimensional

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.delete(arr, 3)

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
np.delete(arr, np.s_[2:4])

array([1, 2, 5, 6, 7, 8])

### Excluindo elementos de um array bidimensional

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.delete(arr, 2, 1) # index x axis => index 2, axis 1 (coluna)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [ ]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
np.delete(arr, np.s_[1:], 0)

array([[1, 2, 3, 4]])

In [ ]:
np.delete(arr, np.s_[1:3], 1)

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
np.delete(arr, 1, None)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Funções Universais da NumPy

Também conhecidas por UFUNC são diversas funções que operam sobre NumPy Arrays em forma de **broadcasting** (transmissão), ou seja, a NumPy irá iterar no array executando a função determinada em cada elemento.

### Funções Matemáticas:

|Função|Descrição
|---|---|
add(x1, x2, /[, out, where, casting, order, …])|Add arguments element-wise.
subtract(x1, x2, /[, out, where, casting, …])|Subtract arguments, element-wise.
multiply(x1, x2, /[, out, where, casting, …])|Multiply arguments element-wise.
divide(x1, x2, /[, out, where, casting, …])|Returns a true division of the inputs, element-wise.
logaddexp(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs.
logaddexp2(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs in base-2.
true_divide(x1, x2, /[, out, where, …])|Returns a true division of the inputs, element-wise.
floor_divide(x1, x2, /[, out, where, …])|Return the largest integer smaller or equal to the division of the inputs.
negative(x, /[, out, where, casting, order, …])|Numerical negative, element-wise.
positive(x, /[, out, where, casting, order, …])|Numerical positive, element-wise.
power(x1, x2, /[, out, where, casting, …])|First array elements raised to powers from second array, element-wise.
remainder(x1, x2, /[, out, where, casting, …])|Return element-wise remainder of division.
mod(x1, x2, /[, out, where, casting, order, …])|Return element-wise remainder of division.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
divmod(x1, x2[, out1, out2], / [[, out, …])|Return element-wise quotient and remainder simultaneously.
absolute(x, /[, out, where, casting, order, …])|Calculate the absolute value element-wise.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
rint(x, /[, out, where, casting, order, …])|Round elements of the array to the nearest integer.
sign(x, /[, out, where, casting, order, …])|Returns an element-wise indication of the sign of a number.
heaviside(x1, x2, /[, out, where, casting, …])|Compute the Heaviside step function.
conj(x, /[, out, where, casting, order, …])|Return the complex conjugate, element-wise.
exp(x, /[, out, where, casting, order, …])|Calculate the exponential of all elements in the input array.
exp2(x, /[, out, where, casting, order, …])|Calculate 2**p for all p in the input array.
log(x, /[, out, where, casting, order, …])|Natural logarithm, element-wise.
log2(x, /[, out, where, casting, order, …])|Base-2 logarithm of x.
log10(x, /[, out, where, casting, order, …])|Return the base 10 logarithm of the input array, element-wise.
expm1(x, /[, out, where, casting, order, …])|Calculate exp(x) - 1 for all elements in the array.
log1p(x, /[, out, where, casting, order, …])|Return the natural logarithm of one plus the input array, element-wise.
sqrt(x, /[, out, where, casting, order, …])|Return the non-negative square-root of an array, element-wise.
square(x, /[, out, where, casting, order, …])|Return the element-wise square of the input.
cbrt(x, /[, out, where, casting, order, …])|Return the cube-root of an array, element-wise.
reciprocal(x, /[, out, where, casting, …])|Return the reciprocal of the argument, element-wise.
gcd(x1, x2, /[, out, where, casting, order, …])|Returns the greatest common divisor of |x1| and |x2|
lcm(x1, x2, /[, out, where, casting, order, …])|Returns the lowest common multiple of |x1| and |x2|


### Funções Trigonométricas:

|Função|Descrição
|---|---|
sin(x, /[, out, where, casting, order, …])|Trigonometric sine, element-wise.
cos(x, /[, out, where, casting, order, …])|Cosine element-wise.
tan(x, /[, out, where, casting, order, …])|Compute tangent element-wise.
arcsin(x, /[, out, where, casting, order, …])|Inverse sine, element-wise.
arccos(x, /[, out, where, casting, order, …])|Trigonometric inverse cosine, element-wise.
arctan(x, /[, out, where, casting, order, …])|Trigonometric inverse tangent, element-wise.
arctan2(x1, x2, /[, out, where, casting, …])|Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
hypot(x1, x2, /[, out, where, casting, …])|Given the “legs” of a right triangle, return its hypotenuse.
sinh(x, /[, out, where, casting, order, …])|Hyperbolic sine, element-wise.
cosh(x, /[, out, where, casting, order, …])|Hyperbolic cosine, element-wise.
tanh(x, /[, out, where, casting, order, …])|Compute hyperbolic tangent element-wise.
arcsinh(x, /[, out, where, casting, order, …])|Inverse hyperbolic sine element-wise.
arccosh(x, /[, out, where, casting, order, …])|Inverse hyperbolic cosine, element-wise.
arctanh(x, /[, out, where, casting, order, …])|Inverse hyperbolic tangent element-wise.
deg2rad(x, /[, out, where, casting, order, …])|Convert angles from degrees to radians.
rad2deg(x, /[, out, where, casting, order, …])|Convert angles from radians to degrees.

### Funções Binárias:

|Função|Descrição
|---|---|
bitwise_and(x1, x2, /[, out, where, …])|Compute the bit-wise AND of two arrays element-wise.
bitwise_or(x1, x2, /[, out, where, casting, …])|Compute the bit-wise OR of two arrays element-wise.
bitwise_xor(x1, x2, /[, out, where, …])|Compute the bit-wise XOR of two arrays element-wise.
invert(x, /[, out, where, casting, order, …])|Compute bit-wise inversion, or bit-wise NOT, element-wise.
left_shift(x1, x2, /[, out, where, casting, …])|Shift the bits of an integer to the left.
right_shift(x1, x2, /[, out, where, …])|Shift the bits of an integer to the right.

### Funções de Comparação:

|Função|Descrição
|---|---|
greater(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 > x2) element-wise.
greater_equal(x1, x2, /[, out, where, …])|Return the truth value of (x1 >= x2) element-wise.
less(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 < x2) element-wise.
less_equal(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 =< x2) element-wise.
not_equal(x1, x2, /[, out, where, casting, …])|Return (x1 != x2) element-wise.
equal(x1, x2, /[, out, where, casting, …])|Return (x1 == x2) element-wise.
logical_and(x1, x2, /[, out, where, …])|Compute the truth value of x1 AND x2 element-wise.
logical_or(x1, x2, /[, out, where, casting, …])|Compute the truth value of x1 OR x2 element-wise.
logical_xor(x1, x2, /[, out, where, …])|Compute the truth value of x1 XOR x2, element-wise.
logical_not(x, /[, out, where, casting, …])|Compute the truth value of NOT x element-wise.
maximum(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
minimum(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.
fmax(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
fmin(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.

### Funções de Ponto Flutuante:

|Função|Descrição
|---|---|
isfinite(x, /[, out, where, casting, order, …])|Test element-wise for finiteness (not infinity or not Not a Number).
isinf(x, /[, out, where, casting, order, …])|Test element-wise for positive or negative infinity.
isnan(x, /[, out, where, casting, order, …])|Test element-wise for NaN and return result as a boolean array.
isnat(x, /[, out, where, casting, order, …])|Test element-wise for NaT (not a time) and return result as a boolean array.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
signbit(x, /[, out, where, casting, order, …])|Returns element-wise True where signbit is set (less than zero).
copysign(x1, x2, /[, out, where, casting, …])|Change the sign of x1 to that of x2, element-wise.
nextafter(x1, x2, /[, out, where, casting, …])|Return the next floating-point value after x1 towards x2, element-wise.
spacing(x, /[, out, where, casting, order, …])|Return the distance between x and the nearest adjacent number.
modf(x[, out1, out2], / [[, out, where, …])|Return the fractional and integral parts of an array, element-wise.
ldexp(x1, x2, /[, out, where, casting, …])|Returns x1 * 2**x2, element-wise.
frexp(x[, out1, out2], / [[, out, where, …])|Decompose the elements of x into mantissa and twos exponent.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
floor(x, /[, out, where, casting, order, …])|Return the floor of the input, element-wise.
ceil(x, /[, out, where, casting, order, …])|Return the ceiling of the input, element-wise.
trunc(x, /[, out, where, casting, order, …])|Return the truncated value of the input, element-wise.



## Operações matemáticas com escalares

Operações com números escalares são possíveis de serem aplicadas à todos os elementos de um NumPy Array

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr[1] = arr[1] * 2 # Multiplicando elementos da linha 1
arr

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [ 7,  8,  9]])

## Operações entre arrays com a mesma forma e número de elementos

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [ ]:
a * b

array([[ 5, 12],
       [21, 32]])

## Operações entre arrays com formas diferentes
Nesta situação a NumPy utiliza-se de um termo denominado difusão (broadcasting), onde o array menor é difundido ao array maior.

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([5, 6])
b

array([5, 6])

In [ ]:
a - b

array([[-4, -4],
       [-2, -2]])

In [ ]:
b - a

array([[4, 4],
       [2, 2]])

## Slicing (Fatiamento)
Todos os elementos de um array, assim como outros tipos de listas do Python podem ser acessados diretamente pelo seu índice.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[0], a[2], a[-1]

(0, 2, 9)

Arrays multidimensionais, os índices são tuplas de inteiros.

In [ ]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
a[1, 2]

0

In [ ]:
a[2, 2]

2

In [ ]:
a[2, 2] = 99

In [ ]:
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0, 99,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step]
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array.

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step]
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array.

In [ ]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
arr[0,3:5]

array([3, 4])

In [ ]:
arr[4:,4:]

array([[44, 45],
       [54, 55]])

In [ ]:
arr[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [ ]:
arr[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Seleção condicional

In [ ]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
mask = (arr % 2) == 0
mask

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [ ]:
arr[mask]

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44, 50, 52,
       54])

In [ ]:
mask1 = (arr % 10) == 0
mask2 = (arr % 25) == 0
arr[(mask1 & mask2)]

array([ 0, 50])

In [ ]:
arr[(mask1 | mask2)]

array([ 0, 10, 20, 25, 30, 40, 50])

In [ ]:
mask3 = arr != 25

In [ ]:
arr[((mask1 | mask2) & mask3)]

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
arr[np.where(np.logical_and(arr > 10, arr < 50))]

array([11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25, 30, 31, 32, 33, 34, 35,
       40, 41, 42, 43, 44, 45])