# Biblioteca NumPy
<hr />

* NumPy é uma biblioteca open source especializada em operações de Álgebra Linear em Python.

* "Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes." [WikiPedia](https://pt.wikipedia.org/wiki/%C3%81lgebra_linear).

* É amplamente utilizada na maioria de outras bibliotecas de análise de dados.

* Seus principais métodos foram desenvolvidos em linguagem C, o que garante alto desempenho, mesmo em vetores com grandes quantidades de informações.

* Sua instalação pode ser feita através do pip ou do conda:
    ```javascript
        pip install numpy ou conda install numpy
    ```


* NumPy Arrays é a principal ferramenta da biblioteca.

* Arrays em NumPy podem ser VETORES ou MATRIZES.

* Vetores são arrays de uma única dimensão, enquato matrizes são arrays de múltiplas dimensões (porém pode existir uma matriz com apenas uma linha ou uma coluna).

* Matrizes podem ser encontradas em objetos comuns do dia a dia como por exemplo uma TV, nada mais é do que uma matriz de pixels, um tabuleiro de xadrez, a tela de um smartfone.

**A primeira tarefa a ser efetuada é importar a biblioteca NumPy. É muito comum criar um alias para o import, facilitando sua utilização.**

In [1]:
import numpy as np

## Criando arrays a partir de listas

In [3]:
lista = [1, 2, 3]
lista

[1, 2, 3]

In [4]:
np.array(lista)

array([1, 2, 3])

## Criando matrizes a partir de listas

In [6]:
matriz = [[1, 2, 3],[5, 6, 7],[8, 9, 10]]


In [8]:
np.array(matriz)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Principais Métodos NumPy

### Método: **arange()**
Semelhante ao range do Python, porém devolve um array com os elementos que estão dentro do intervalo selecionado.

*Dica: ao digitar o nome do método, o comando shift+tab mostra a documentação!*

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Método: zeros()

Retorna uma matriz com a dimensão informada, preenchido com zeros.

In [13]:
np.zeros(3)

array([0., 0., 0.])

O tipo padrão é float, porém pode ser alterado pelo parâmetro **dtype**.

In [14]:
np.zeros(3, dtype=int)

array([0, 0, 0])

Para uma matriz com mais de uma dimensão, o parâmetro com as dimensões deverá ser uma tupla.

In [15]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Método: ones()

Da mesma forma do método *zeros()*, retorna uma matriz com a dimensão informada, preenchida com 1.

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones(3, dtype=int)

array([1, 1, 1])

### Método: linspace()

Cria uma sequencia de números igualmente espaçados entre os limites dados.

In [19]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [20]:
np.linspace(0, 100, 10, dtype=int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

### Método: eye()

Retorna a **matriz identidade** com a dimensão informada.

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Sub-biblioteca random

Sub-biblioteca do NumPy com diversos métodos para geração de números aleatórios.

### Método: rand()

Retorna uma matriz com a dimensão informada, preenchidas com números aleatórios de 0 a 1 seguindo uma distribuição uniforme (probabilidade).

In [23]:
np.random.rand(5)

array([8.92812893e-01, 7.53665025e-01, 6.24396975e-04, 3.79958691e-01,
       2.30163104e-01])

In [24]:
np.random.rand(5, 3)

array([[0.46726998, 0.53448815, 0.51834387],
       [0.97549503, 0.87137515, 0.15619431],
       [0.6614644 , 0.08193421, 0.34814071],
       [0.22326888, 0.87421238, 0.22560828],
       [0.63262418, 0.44370473, 0.32081412]])

É possível incluir operações na criação de números aleatórios

In [25]:
np.random.rand(5) * 100   # list(map(lambda i: * 2, lista))

array([55.38874969, 51.36887242,  8.0541545 , 74.09008978, 65.17484523])

### Método: randn()

Retorna uma matriz com a dimensão informada, preenchida com números aleatórios, seguindo uma distribuição normal.

In [26]:
np.random.randn(5)

array([-0.35481615,  0.05923462,  0.45000282,  0.04430082, -0.33141428])

In [27]:
np.random.randn(3, 4)

array([[-1.38435377,  0.13674462,  1.15556073, -1.79039439],
       [-0.54296199, -0.11481791,  0.59613774, -0.77262827],
       [-0.97005098, -0.47361835, -0.89256454, -0.49441892]])

### Método: randint()

Retorna um número inteiro aleatório entre o intervalo informado ou uma matriz unidimensional, preenchida com números aleatórios inteiros, entre o intervalo informado.

In [30]:
np.random.randint(1, 10)

8

In [31]:
np.random.randint(1, 100, 15)

array([88, 34, 86, 78, 95, 80, 60,  2, 54, 76, 20, 77, 60, 25, 21])

## Métodos e atributos do objeto NumPy Array

### Método: reshape()

Reorganiza um array em uma dimensão diferente da original.

In [33]:
myarray = np.random.rand(10)  # 1 linha
myarray

array([0.14055972, 0.85666926, 0.00985372, 0.93840237, 0.10598785,
       0.24532916, 0.86634714, 0.08474161, 0.70475659, 0.49980348])

In [35]:
myarray.reshape(5, 2).reshape(2, 5)

array([[0.14055972, 0.85666926, 0.00985372, 0.93840237, 0.10598785],
       [0.24532916, 0.86634714, 0.08474161, 0.70475659, 0.49980348]])

### Método: max()

Retorna o maior valor dentro de um array.

In [36]:
myarray.max()

0.9384023681111066

### Método: argmax()

Retorna o índice do maior valor dentro de um array.

In [37]:
myarray.argmax()

3

### Método: min()

Retorna o menor valor dentro de um array.

In [38]:
myarray.min()

0.009853718349614793

### Método: argmin()

Retorna o índice do menor valor dentro de um array.

In [39]:
myarray.argmin()

2

### Atributo: shape

Retorna o formado do array.

In [47]:
myarray.shape

(10,)

In [54]:
a = np.random.rand(3, 4)
a

array([[0.70071118, 0.61322713, 0.4814376 , 0.5285465 ],
       [0.77140441, 0.04822508, 0.23155526, 0.69974597],
       [0.02075315, 0.60589495, 0.04967813, 0.17348984]])

In [55]:
a.shape

(3, 4)

## Mais métodos do objeto NumPy Array

### Método: mean()
Retorna a média aritmética simples dos elementos do array

In [56]:
a= np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [58]:
a.mean()

2.5

In [59]:
a = np.array([[1,2],[3,4],[5,6]])
a.mean()

3.5

### Método: std()
Retorna o desvio padrão

In [62]:
a= np.array([1, 2, 3, 4])
a.std()

1.118033988749895

### Método: sum()

In [63]:
a= np.array([1, 2, 3, 4])
a.sum()

10

In [65]:
a = np.array([[1, 2],[3, 4], [99, 777]])
a.sum()

886

In [66]:
a.sum(axis = 0)

array([103, 783])

In [67]:
a.sum(axis = 1)

array([  3,   7, 876])

## Inserindo e excluindo elementos

### Inserindo elementos de um array unidimensional

In [72]:
arr = np.array([1, 2, 3, 5, 6, 7, 8])
arr

array([1, 2, 3, 5, 6, 7, 8])

In [73]:
np.insert(arr, 3, 4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.insert(arr, 3, [99, 100, 98, 76])

array([  1,   2,   3,  99, 100,  98,  76,   5,   6,   7,   8])

In [75]:
np.insert(arr, (3,6), [88, 55])

array([ 1,  2,  3, 88,  5,  6,  7, 55,  8])

### Inserindo elementos de um array bidimensional

In [77]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.insert(arr, 1, [6, 9, 8, 10], axis =0 )

array([[ 0,  1,  2,  3],
       [ 6,  9,  8, 10],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
np.insert(arr, 1, [[6], [9]], axis = 0)

array([[ 0,  1,  2,  3],
       [ 6,  6,  6,  6],
       [ 9,  9,  9,  9],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
np.insert(arr, [1], [[8], [7], [11]], axis=1)

array([[ 0,  8,  1,  2,  3],
       [ 4,  7,  5,  6,  7],
       [ 8, 11,  9, 10, 11]])

In [81]:
np.insert(arr, [1], [8, 7, 11], axis=1)

array([[ 0,  8,  7, 11,  1,  2,  3],
       [ 4,  8,  7, 11,  5,  6,  7],
       [ 8,  8,  7, 11,  9, 10, 11]])

### Excluindo elementos de um array unidimensional

In [86]:
arr= (1,2,3,4,5,6,7,8)
np.delete(arr, 3)

array([1, 2, 3, 5, 6, 7, 8])

In [87]:
np.delete(arr, np.s_[2:4])

array([1, 2, 5, 6, 7, 8])

### Excluindo elementos de um array bidimensional

In [88]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [89]:
np.delete(arr, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [90]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [92]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
np.delete(arr, np.s_[1:3], 0)

array([[1, 2, 3, 4]])

In [94]:
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
np.delete(arr, np.s_[1:3], 1)

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [96]:
np.delete(arr, np.s_[1::2], 1)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

## Funções Universais da NumPy

Também conhecidas por UFUNC são diversas funções que operam sobre NumPy Arrays em forma de **broadcasting** (transmissão), ou seja, a NumPy irá iterar no array executando a função determinada em cada elemento.

### Funções Matemáticas:

|Função|Descrição
|---|---|
add(x1, x2, /[, out, where, casting, order, …])|Add arguments element-wise.
subtract(x1, x2, /[, out, where, casting, …])|Subtract arguments, element-wise.
multiply(x1, x2, /[, out, where, casting, …])|Multiply arguments element-wise.
divide(x1, x2, /[, out, where, casting, …])|Returns a true division of the inputs, element-wise.
logaddexp(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs.
logaddexp2(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs in base-2.
true_divide(x1, x2, /[, out, where, …])|Returns a true division of the inputs, element-wise.
floor_divide(x1, x2, /[, out, where, …])|Return the largest integer smaller or equal to the division of the inputs.
negative(x, /[, out, where, casting, order, …])|Numerical negative, element-wise.
positive(x, /[, out, where, casting, order, …])|Numerical positive, element-wise.
power(x1, x2, /[, out, where, casting, …])|First array elements raised to powers from second array, element-wise.
remainder(x1, x2, /[, out, where, casting, …])|Return element-wise remainder of division.
mod(x1, x2, /[, out, where, casting, order, …])|Return element-wise remainder of division.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
divmod(x1, x2[, out1, out2], / [[, out, …])|Return element-wise quotient and remainder simultaneously.
absolute(x, /[, out, where, casting, order, …])|Calculate the absolute value element-wise.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
rint(x, /[, out, where, casting, order, …])|Round elements of the array to the nearest integer.
sign(x, /[, out, where, casting, order, …])|Returns an element-wise indication of the sign of a number.
heaviside(x1, x2, /[, out, where, casting, …])|Compute the Heaviside step function.
conj(x, /[, out, where, casting, order, …])|Return the complex conjugate, element-wise.
exp(x, /[, out, where, casting, order, …])|Calculate the exponential of all elements in the input array.
exp2(x, /[, out, where, casting, order, …])|Calculate 2**p for all p in the input array.
log(x, /[, out, where, casting, order, …])|Natural logarithm, element-wise.
log2(x, /[, out, where, casting, order, …])|Base-2 logarithm of x.
log10(x, /[, out, where, casting, order, …])|Return the base 10 logarithm of the input array, element-wise.
expm1(x, /[, out, where, casting, order, …])|Calculate exp(x) - 1 for all elements in the array.
log1p(x, /[, out, where, casting, order, …])|Return the natural logarithm of one plus the input array, element-wise.
sqrt(x, /[, out, where, casting, order, …])|Return the non-negative square-root of an array, element-wise.
square(x, /[, out, where, casting, order, …])|Return the element-wise square of the input.
cbrt(x, /[, out, where, casting, order, …])|Return the cube-root of an array, element-wise.
reciprocal(x, /[, out, where, casting, …])|Return the reciprocal of the argument, element-wise.
gcd(x1, x2, /[, out, where, casting, order, …])|Returns the greatest common divisor of |x1| and |x2|
lcm(x1, x2, /[, out, where, casting, order, …])|Returns the lowest common multiple of |x1| and |x2|


### Funções Trigonométricas:

|Função|Descrição
|---|---|
sin(x, /[, out, where, casting, order, …])|Trigonometric sine, element-wise.
cos(x, /[, out, where, casting, order, …])|Cosine element-wise.
tan(x, /[, out, where, casting, order, …])|Compute tangent element-wise.
arcsin(x, /[, out, where, casting, order, …])|Inverse sine, element-wise.
arccos(x, /[, out, where, casting, order, …])|Trigonometric inverse cosine, element-wise.
arctan(x, /[, out, where, casting, order, …])|Trigonometric inverse tangent, element-wise.
arctan2(x1, x2, /[, out, where, casting, …])|Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
hypot(x1, x2, /[, out, where, casting, …])|Given the “legs” of a right triangle, return its hypotenuse.
sinh(x, /[, out, where, casting, order, …])|Hyperbolic sine, element-wise.
cosh(x, /[, out, where, casting, order, …])|Hyperbolic cosine, element-wise.
tanh(x, /[, out, where, casting, order, …])|Compute hyperbolic tangent element-wise.
arcsinh(x, /[, out, where, casting, order, …])|Inverse hyperbolic sine element-wise.
arccosh(x, /[, out, where, casting, order, …])|Inverse hyperbolic cosine, element-wise.
arctanh(x, /[, out, where, casting, order, …])|Inverse hyperbolic tangent element-wise.
deg2rad(x, /[, out, where, casting, order, …])|Convert angles from degrees to radians.
rad2deg(x, /[, out, where, casting, order, …])|Convert angles from radians to degrees.

### Funções Binárias:

|Função|Descrição
|---|---|
bitwise_and(x1, x2, /[, out, where, …])|Compute the bit-wise AND of two arrays element-wise.
bitwise_or(x1, x2, /[, out, where, casting, …])|Compute the bit-wise OR of two arrays element-wise.
bitwise_xor(x1, x2, /[, out, where, …])|Compute the bit-wise XOR of two arrays element-wise.
invert(x, /[, out, where, casting, order, …])|Compute bit-wise inversion, or bit-wise NOT, element-wise.
left_shift(x1, x2, /[, out, where, casting, …])|Shift the bits of an integer to the left.
right_shift(x1, x2, /[, out, where, …])|Shift the bits of an integer to the right.

### Funções de Comparação:

|Função|Descrição
|---|---|
greater(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 > x2) element-wise.
greater_equal(x1, x2, /[, out, where, …])|Return the truth value of (x1 >= x2) element-wise.
less(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 < x2) element-wise.
less_equal(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 =< x2) element-wise.
not_equal(x1, x2, /[, out, where, casting, …])|Return (x1 != x2) element-wise.
equal(x1, x2, /[, out, where, casting, …])|Return (x1 == x2) element-wise.
logical_and(x1, x2, /[, out, where, …])|Compute the truth value of x1 AND x2 element-wise.
logical_or(x1, x2, /[, out, where, casting, …])|Compute the truth value of x1 OR x2 element-wise.
logical_xor(x1, x2, /[, out, where, …])|Compute the truth value of x1 XOR x2, element-wise.
logical_not(x, /[, out, where, casting, …])|Compute the truth value of NOT x element-wise.
maximum(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
minimum(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.
fmax(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
fmin(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.

### Funções de Ponto Flutuante:

|Função|Descrição
|---|---|
isfinite(x, /[, out, where, casting, order, …])|Test element-wise for finiteness (not infinity or not Not a Number).
isinf(x, /[, out, where, casting, order, …])|Test element-wise for positive or negative infinity.
isnan(x, /[, out, where, casting, order, …])|Test element-wise for NaN and return result as a boolean array.
isnat(x, /[, out, where, casting, order, …])|Test element-wise for NaT (not a time) and return result as a boolean array.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
signbit(x, /[, out, where, casting, order, …])|Returns element-wise True where signbit is set (less than zero).
copysign(x1, x2, /[, out, where, casting, …])|Change the sign of x1 to that of x2, element-wise.
nextafter(x1, x2, /[, out, where, casting, …])|Return the next floating-point value after x1 towards x2, element-wise.
spacing(x, /[, out, where, casting, order, …])|Return the distance between x and the nearest adjacent number.
modf(x[, out1, out2], / [[, out, where, …])|Return the fractional and integral parts of an array, element-wise.
ldexp(x1, x2, /[, out, where, casting, …])|Returns x1 * 2**x2, element-wise.
frexp(x[, out1, out2], / [[, out, where, …])|Decompose the elements of x into mantissa and twos exponent.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
floor(x, /[, out, where, casting, order, …])|Return the floor of the input, element-wise.
ceil(x, /[, out, where, casting, order, …])|Return the ceiling of the input, element-wise.
trunc(x, /[, out, where, casting, order, …])|Return the truncated value of the input, element-wise.



## Operações matemáticas com escalares

Operações com números escalares são possíveis de serem aplicadas à todos os elementos de um NumPy Array

In [99]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Operações entre arrays com a mesma forma e número de elementos

In [102]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [103]:
a*b

array([[ 5, 12],
       [21, 32]])

## Operações entre arrays com formas diferentes
Nesta situação a NumPy utiliza-se de um termo denominado difusão (broadcasting), onde o array menor é difundido ao array maior.

In [105]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])


In [106]:
a - b

array([[-4, -4],
       [-2, -2]])

In [107]:
b - a

array([[4, 4],
       [2, 2]])

## Slicing (Fatiamento)
Todos os elementos de um array, assim como outros tipos de listas do Python podem ser acessados diretamente pelo seu índice.

In [108]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
a[0], a[2]

(0, 2)

In [111]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [112]:
a[2,2]

2

Arrays multidimensionais, os índices são tuplas de inteiros.

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step]
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array.

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step]
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array.

In [ ]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])

## Seleção condicional

In [118]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])


In [114]:
arr[0, 3:5]

array([3, 4])

In [121]:
arr[2::,1::2]

array([[21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])