## A4 - Exercícios Numpy (Parte 1)

<hr />

In [ ]:
import numpy as np

1 - Crie um vetor com 10 elementos 0.

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

In [ ]:
a = np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2 - Crie um vetor com 10 elementos 0 e inicialize o quinto elemento com o valor 1.

```
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
```

In [ ]:
a = np.zeros((10))
a[4]=1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

3 - Crie um vetor com valores em sequencia de 10 à 49.

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])
```

In [ ]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4 - Crie um vetor com valores inteiros de 50 à 0.

```
array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```


In [ ]:
np.arange(50, -1, -1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

5 - Crie um vetor com valores inteiros de 0 à 49 em seguida inverta a orderm do vetor.

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
       
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```

In [ ]:
a = np.arange(0, 50)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
b = np.arange(49, -1, -1)
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

6 - Crie uma matriz 3 x 3 com valores de 1 à 9.

```
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7 - Dada o vetor [1, 3, 0, 3, 0, 3, 2, 0, 1, 0], descubra os índices dos elementos diferentes de zero.

```
array([0, 1, 3, 5, 6, 8], dtype=int64)
```

In [ ]:
np.nonzero(np.array([1, 3, 0, 3, 0, 3, 2, 0, 1, 0]))

(array([0, 1, 3, 5, 6, 8]),)

8 - Crie uma matriz 3 x 3 x 3 com números aleatórios.

```
array([[[0.61286554, 0.74921735, 0.61223858],
        [0.96047489, 0.65628431, 0.79342544],
        [0.70941175, 0.98583943, 0.00318382]],

       [[0.85867772, 0.93941609, 0.30006033],
        [0.79160418, 0.0865738 , 0.69892442],
        [0.33265707, 0.25932833, 0.11447914]],

       [[0.24026643, 0.23737787, 0.04470459],
        [0.11646793, 0.32991814, 0.85027852],
        [0.25262905, 0.1805445 , 0.40050341]]])
```

In [ ]:
np.random.random((3,3,3))

array([[[0.66393689, 0.5704975 , 0.63420097],
        [0.97966793, 0.25087841, 0.5582125 ],
        [0.95795702, 0.96199267, 0.54865029]],

       [[0.54898629, 0.57213206, 0.7250154 ],
        [0.85162131, 0.49435578, 0.56174359],
        [0.21893246, 0.28859841, 0.75991778]],

       [[0.61017507, 0.90366894, 0.80481333],
        [0.20601569, 0.76552439, 0.25107624],
        [0.13125689, 0.38693916, 0.70558552]]])

9 - Crie um vetor de tamanho 10 com números aleatórios em ordenados em ordem crescente.

Exemplo:
```
array([0.56239709, 0.36663249, 0.24432617, 0.43788321, 0.89709646,
       0.58901959, 0.26398762, 0.82502151, 0.3666227 , 0.47548132])
       
array([0.24432617, 0.26398762, 0.3666227 , 0.36663249, 0.43788321,
       0.47548132, 0.56239709, 0.58901959, 0.82502151, 0.89709646])
```

In [ ]:
a = np.random.rand(10)
a



array([0.4318776 , 0.83891399, 0.12653656, 0.05452445, 0.32541286,
       0.60485187, 0.30744635, 0.02983402, 0.41768701, 0.07025102])

In [ ]:
a.sort()
a

array([0.02983402, 0.05452445, 0.07025102, 0.12653656, 0.30744635,
       0.32541286, 0.41768701, 0.4318776 , 0.60485187, 0.83891399])